/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ActionType = { 'goal' : null } |
  { 'join' : null } |
  { 'status_change' : null } |
  { 'follow_team' : null } |
  { 'follow_player' : null };
export type ActivityId = bigint;
export interface ActivityItem {
  'id' : ActivityId,
  'actorName' : string,
  'actionType' : ActionType,
  'entityId' : bigint,
  'timestamp' : Timestamp,
  'entityName' : string,
  'actorPrincipal' : [] | [Principal],
}
export interface Match {
  'id' : MatchId,
  'matchTime' : string,
  'status' : MatchStatus,
  'awayTeamId' : TeamId,
  'homeTeamId' : TeamId,
  'joiners' : Array<Principal>,
  'homeScore' : bigint,
  'awayScore' : bigint,
  'matchDate' : string,
}
export type MatchId = bigint;
export type MatchStatus = { 'scheduled' : null } |
  { 'live' : null } |
  { 'finished' : null };
export interface NewsArticle {
  'id' : NewsId,
  'title' : string,
  'content' : string,
  'date' : string,
  'emoji' : string,
  'excerpt' : string,
  'category' : string,
}
export type NewsId = bigint;
export interface Official {
  'id' : OfficialId,
  'area' : string,
  'name' : string,
  'role' : string,
  'email' : string,
  'phone' : string,
}
export type OfficialId = bigint;
export interface Player {
  'id' : PlayerId,
  'assists' : bigint,
  'name' : string,
  'yellowCards' : bigint,
  'goals' : bigint,
  'teamId' : TeamId,
  'position' : string,
}
export type PlayerId = bigint;
export interface Referee {
  'id' : RefereeId,
  'status' : RefereeStatus,
  'assignedMatchIds' : Array<MatchId>,
  'name' : string,
  'licenseNumber' : string,
  'phone' : string,
}
export type RefereeId = bigint;
export type RefereeStatus = { 'active' : null } |
  { 'inactive' : null };
export interface Standing {
  'goalDiff' : bigint,
  'played' : bigint,
  'wins' : bigint,
  'goalsFor' : bigint,
  'losses' : bigint,
  'goalsAgainst' : bigint,
  'teamId' : TeamId,
  'position' : bigint,
  'draws' : bigint,
  'points' : bigint,
}
export interface Team {
  'id' : TeamId,
  'name' : string,
  'wins' : bigint,
  'goalsFor' : bigint,
  'losses' : bigint,
  'emoji' : string,
  'abbreviation' : string,
  'goalsAgainst' : bigint,
  'draws' : bigint,
}
export type TeamId = bigint;
export type Timestamp = bigint;
export interface UserProfilePublic {
  'favouriteTeamId' : [] | [TeamId],
  'displayName' : string,
  'teamAffiliation' : string,
  'areaOfResidence' : string,
  'followedPlayerIds' : Array<PlayerId>,
  'followedTeamIds' : Array<TeamId>,
}
export interface _SERVICE {
  'addMatch' : ActorMethod<[bigint, bigint, string, string], bigint>,
  'addNews' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'addOfficial' : ActorMethod<[string, string, string, string, string], bigint>,
  'addPlayer' : ActorMethod<
    [string, bigint, string, bigint, bigint, bigint],
    bigint
  >,
  'addReferee' : ActorMethod<[string, string, string], bigint>,
  'addTeam' : ActorMethod<[string, string, string], bigint>,
  'assignRefereeToMatch' : ActorMethod<[bigint, bigint], boolean>,
  'deleteNews' : ActorMethod<[bigint], boolean>,
  'deleteOfficial' : ActorMethod<[bigint], boolean>,
  'deletePlayer' : ActorMethod<[bigint], boolean>,
  'deleteReferee' : ActorMethod<[bigint], boolean>,
  'deleteTeam' : ActorMethod<[bigint], boolean>,
  'dismissActivity' : ActorMethod<[bigint], undefined>,
  'followPlayer' : ActorMethod<[bigint], undefined>,
  'followTeam' : ActorMethod<[bigint], undefined>,
  'getActivities' : ActorMethod<[], Array<ActivityItem>>,
  'getAllMatches' : ActorMethod<[], Array<Match>>,
  'getAllNews' : ActorMethod<[], Array<NewsArticle>>,
  'getAllOfficials' : ActorMethod<[], Array<Official>>,
  'getAllPlayers' : ActorMethod<[], Array<Player>>,
  'getAllReferees' : ActorMethod<[], Array<Referee>>,
  'getAllTeams' : ActorMethod<[], Array<Team>>,
  'getArticle' : ActorMethod<[bigint], [] | [NewsArticle]>,
  'getMatch' : ActorMethod<[bigint], [] | [Match]>,
  'getMatchesByTeam' : ActorMethod<[bigint], Array<Match>>,
  'getOfficial' : ActorMethod<[bigint], [] | [Official]>,
  'getPlayer' : ActorMethod<[bigint], [] | [Player]>,
  'getPlayersByTeam' : ActorMethod<[bigint], Array<Player>>,
  'getReferee' : ActorMethod<[bigint], [] | [Referee]>,
  'getStandings' : ActorMethod<[], Array<Standing>>,
  'getTeam' : ActorMethod<[bigint], [] | [Team]>,
  'getUserDismissed' : ActorMethod<[], Array<bigint>>,
  'getUserProfile' : ActorMethod<[], UserProfilePublic>,
  'hasJoinedMatch' : ActorMethod<[bigint], boolean>,
  'joinMatch' : ActorMethod<[bigint], { 'ok' : null } | { 'err' : string }>,
  'scheduleMatch' : ActorMethod<[bigint, bigint, string, string], bigint>,
  'setFavouriteTeam' : ActorMethod<[bigint], undefined>,
  'unassignRefereeFromMatch' : ActorMethod<[bigint, bigint], boolean>,
  'unfollowPlayer' : ActorMethod<[bigint], undefined>,
  'unfollowTeam' : ActorMethod<[bigint], undefined>,
  'updateMatchScore' : ActorMethod<[bigint, bigint, bigint], boolean>,
  'updateMatchStatus' : ActorMethod<[bigint, MatchStatus], boolean>,
  'updateNews' : ActorMethod<
    [bigint, string, string, string, string, string, string],
    boolean
  >,
  'updateOfficial' : ActorMethod<
    [bigint, string, string, string, string, string],
    boolean
  >,
  'updatePlayer' : ActorMethod<
    [bigint, string, bigint, string, bigint, bigint, bigint],
    boolean
  >,
  'updateReferee' : ActorMethod<
    [bigint, string, string, RefereeStatus, string],
    boolean
  >,
  'updateTeam' : ActorMethod<
    [bigint, string, string, string, bigint, bigint, bigint, bigint, bigint],
    boolean
  >,
  'updateUserProfile' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];