/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ActivityId = IDL.Nat;
export const ActionType = IDL.Variant({
  'goal' : IDL.Null,
  'join' : IDL.Null,
  'status_change' : IDL.Null,
  'follow_team' : IDL.Null,
  'follow_player' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const ActivityItem = IDL.Record({
  'id' : ActivityId,
  'actorName' : IDL.Text,
  'actionType' : ActionType,
  'entityId' : IDL.Nat,
  'timestamp' : Timestamp,
  'entityName' : IDL.Text,
  'actorPrincipal' : IDL.Opt(IDL.Principal),
});
export const MatchId = IDL.Nat;
export const MatchStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'live' : IDL.Null,
  'finished' : IDL.Null,
});
export const TeamId = IDL.Nat;
export const Match = IDL.Record({
  'id' : MatchId,
  'matchTime' : IDL.Text,
  'status' : MatchStatus,
  'awayTeamId' : TeamId,
  'homeTeamId' : TeamId,
  'joiners' : IDL.Vec(IDL.Principal),
  'homeScore' : IDL.Nat,
  'awayScore' : IDL.Nat,
  'matchDate' : IDL.Text,
});
export const NewsId = IDL.Nat;
export const NewsArticle = IDL.Record({
  'id' : NewsId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Text,
  'emoji' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const OfficialId = IDL.Nat;
export const Official = IDL.Record({
  'id' : OfficialId,
  'area' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const PlayerId = IDL.Nat;
export const Player = IDL.Record({
  'id' : PlayerId,
  'assists' : IDL.Nat,
  'name' : IDL.Text,
  'yellowCards' : IDL.Nat,
  'goals' : IDL.Nat,
  'teamId' : TeamId,
  'position' : IDL.Text,
});
export const RefereeId = IDL.Nat;
export const RefereeStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const Referee = IDL.Record({
  'id' : RefereeId,
  'status' : RefereeStatus,
  'assignedMatchIds' : IDL.Vec(MatchId),
  'name' : IDL.Text,
  'licenseNumber' : IDL.Text,
  'phone' : IDL.Text,
});
export const Team = IDL.Record({
  'id' : TeamId,
  'name' : IDL.Text,
  'wins' : IDL.Nat,
  'goalsFor' : IDL.Nat,
  'losses' : IDL.Nat,
  'emoji' : IDL.Text,
  'abbreviation' : IDL.Text,
  'goalsAgainst' : IDL.Nat,
  'draws' : IDL.Nat,
});
export const Standing = IDL.Record({
  'goalDiff' : IDL.Int,
  'played' : IDL.Nat,
  'wins' : IDL.Nat,
  'goalsFor' : IDL.Nat,
  'losses' : IDL.Nat,
  'goalsAgainst' : IDL.Nat,
  'teamId' : TeamId,
  'position' : IDL.Nat,
  'draws' : IDL.Nat,
  'points' : IDL.Nat,
});
export const UserProfilePublic = IDL.Record({
  'favouriteTeamId' : IDL.Opt(TeamId),
  'displayName' : IDL.Text,
  'teamAffiliation' : IDL.Text,
  'areaOfResidence' : IDL.Text,
  'followedPlayerIds' : IDL.Vec(PlayerId),
  'followedTeamIds' : IDL.Vec(TeamId),
});

export const idlService = IDL.Service({
  'addMatch' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addNews' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addOfficial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addPlayer' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'addReferee' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addTeam' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'assignRefereeToMatch' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'deleteNews' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteOfficial' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deletePlayer' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteReferee' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteTeam' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'dismissActivity' : IDL.Func([IDL.Nat], [], []),
  'followPlayer' : IDL.Func([IDL.Nat], [], []),
  'followTeam' : IDL.Func([IDL.Nat], [], []),
  'getActivities' : IDL.Func([], [IDL.Vec(ActivityItem)], ['query']),
  'getAllMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'getAllNews' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
  'getAllOfficials' : IDL.Func([], [IDL.Vec(Official)], ['query']),
  'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getAllReferees' : IDL.Func([], [IDL.Vec(Referee)], ['query']),
  'getAllTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
  'getArticle' : IDL.Func([IDL.Nat], [IDL.Opt(NewsArticle)], ['query']),
  'getMatch' : IDL.Func([IDL.Nat], [IDL.Opt(Match)], ['query']),
  'getMatchesByTeam' : IDL.Func([IDL.Nat], [IDL.Vec(Match)], ['query']),
  'getOfficial' : IDL.Func([IDL.Nat], [IDL.Opt(Official)], ['query']),
  'getPlayer' : IDL.Func([IDL.Nat], [IDL.Opt(Player)], ['query']),
  'getPlayersByTeam' : IDL.Func([IDL.Nat], [IDL.Vec(Player)], ['query']),
  'getReferee' : IDL.Func([IDL.Nat], [IDL.Opt(Referee)], ['query']),
  'getStandings' : IDL.Func([], [IDL.Vec(Standing)], ['query']),
  'getTeam' : IDL.Func([IDL.Nat], [IDL.Opt(Team)], ['query']),
  'getUserDismissed' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getUserProfile' : IDL.Func([], [UserProfilePublic], ['query']),
  'hasJoinedMatch' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'joinMatch' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'scheduleMatch' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'setFavouriteTeam' : IDL.Func([IDL.Nat], [], []),
  'unassignRefereeFromMatch' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'unfollowPlayer' : IDL.Func([IDL.Nat], [], []),
  'unfollowTeam' : IDL.Func([IDL.Nat], [], []),
  'updateMatchScore' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'updateMatchStatus' : IDL.Func([IDL.Nat, MatchStatus], [IDL.Bool], []),
  'updateNews' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateOfficial' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updatePlayer' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'updateReferee' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, RefereeStatus, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateTeam' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
      ],
      [IDL.Bool],
      [],
    ),
  'updateUserProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ActivityId = IDL.Nat;
  const ActionType = IDL.Variant({
    'goal' : IDL.Null,
    'join' : IDL.Null,
    'status_change' : IDL.Null,
    'follow_team' : IDL.Null,
    'follow_player' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const ActivityItem = IDL.Record({
    'id' : ActivityId,
    'actorName' : IDL.Text,
    'actionType' : ActionType,
    'entityId' : IDL.Nat,
    'timestamp' : Timestamp,
    'entityName' : IDL.Text,
    'actorPrincipal' : IDL.Opt(IDL.Principal),
  });
  const MatchId = IDL.Nat;
  const MatchStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'live' : IDL.Null,
    'finished' : IDL.Null,
  });
  const TeamId = IDL.Nat;
  const Match = IDL.Record({
    'id' : MatchId,
    'matchTime' : IDL.Text,
    'status' : MatchStatus,
    'awayTeamId' : TeamId,
    'homeTeamId' : TeamId,
    'joiners' : IDL.Vec(IDL.Principal),
    'homeScore' : IDL.Nat,
    'awayScore' : IDL.Nat,
    'matchDate' : IDL.Text,
  });
  const NewsId = IDL.Nat;
  const NewsArticle = IDL.Record({
    'id' : NewsId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Text,
    'emoji' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const OfficialId = IDL.Nat;
  const Official = IDL.Record({
    'id' : OfficialId,
    'area' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const PlayerId = IDL.Nat;
  const Player = IDL.Record({
    'id' : PlayerId,
    'assists' : IDL.Nat,
    'name' : IDL.Text,
    'yellowCards' : IDL.Nat,
    'goals' : IDL.Nat,
    'teamId' : TeamId,
    'position' : IDL.Text,
  });
  const RefereeId = IDL.Nat;
  const RefereeStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const Referee = IDL.Record({
    'id' : RefereeId,
    'status' : RefereeStatus,
    'assignedMatchIds' : IDL.Vec(MatchId),
    'name' : IDL.Text,
    'licenseNumber' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Team = IDL.Record({
    'id' : TeamId,
    'name' : IDL.Text,
    'wins' : IDL.Nat,
    'goalsFor' : IDL.Nat,
    'losses' : IDL.Nat,
    'emoji' : IDL.Text,
    'abbreviation' : IDL.Text,
    'goalsAgainst' : IDL.Nat,
    'draws' : IDL.Nat,
  });
  const Standing = IDL.Record({
    'goalDiff' : IDL.Int,
    'played' : IDL.Nat,
    'wins' : IDL.Nat,
    'goalsFor' : IDL.Nat,
    'losses' : IDL.Nat,
    'goalsAgainst' : IDL.Nat,
    'teamId' : TeamId,
    'position' : IDL.Nat,
    'draws' : IDL.Nat,
    'points' : IDL.Nat,
  });
  const UserProfilePublic = IDL.Record({
    'favouriteTeamId' : IDL.Opt(TeamId),
    'displayName' : IDL.Text,
    'teamAffiliation' : IDL.Text,
    'areaOfResidence' : IDL.Text,
    'followedPlayerIds' : IDL.Vec(PlayerId),
    'followedTeamIds' : IDL.Vec(TeamId),
  });
  
  return IDL.Service({
    'addMatch' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addNews' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addOfficial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addPlayer' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'addReferee' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addTeam' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'assignRefereeToMatch' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'deleteNews' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteOfficial' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deletePlayer' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteReferee' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteTeam' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'dismissActivity' : IDL.Func([IDL.Nat], [], []),
    'followPlayer' : IDL.Func([IDL.Nat], [], []),
    'followTeam' : IDL.Func([IDL.Nat], [], []),
    'getActivities' : IDL.Func([], [IDL.Vec(ActivityItem)], ['query']),
    'getAllMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'getAllNews' : IDL.Func([], [IDL.Vec(NewsArticle)], ['query']),
    'getAllOfficials' : IDL.Func([], [IDL.Vec(Official)], ['query']),
    'getAllPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getAllReferees' : IDL.Func([], [IDL.Vec(Referee)], ['query']),
    'getAllTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
    'getArticle' : IDL.Func([IDL.Nat], [IDL.Opt(NewsArticle)], ['query']),
    'getMatch' : IDL.Func([IDL.Nat], [IDL.Opt(Match)], ['query']),
    'getMatchesByTeam' : IDL.Func([IDL.Nat], [IDL.Vec(Match)], ['query']),
    'getOfficial' : IDL.Func([IDL.Nat], [IDL.Opt(Official)], ['query']),
    'getPlayer' : IDL.Func([IDL.Nat], [IDL.Opt(Player)], ['query']),
    'getPlayersByTeam' : IDL.Func([IDL.Nat], [IDL.Vec(Player)], ['query']),
    'getReferee' : IDL.Func([IDL.Nat], [IDL.Opt(Referee)], ['query']),
    'getStandings' : IDL.Func([], [IDL.Vec(Standing)], ['query']),
    'getTeam' : IDL.Func([IDL.Nat], [IDL.Opt(Team)], ['query']),
    'getUserDismissed' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getUserProfile' : IDL.Func([], [UserProfilePublic], ['query']),
    'hasJoinedMatch' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'joinMatch' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'scheduleMatch' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'setFavouriteTeam' : IDL.Func([IDL.Nat], [], []),
    'unassignRefereeFromMatch' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'unfollowPlayer' : IDL.Func([IDL.Nat], [], []),
    'unfollowTeam' : IDL.Func([IDL.Nat], [], []),
    'updateMatchScore' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'updateMatchStatus' : IDL.Func([IDL.Nat, MatchStatus], [IDL.Bool], []),
    'updateNews' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateOfficial' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updatePlayer' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'updateReferee' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, RefereeStatus, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateTeam' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [IDL.Bool],
        [],
      ),
    'updateUserProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };