/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Player {
    id: PlayerId;
    assists: bigint;
    name: string;
    yellowCards: bigint;
    goals: bigint;
    teamId: TeamId;
    position: string;
}
export type Timestamp = bigint;
export type NewsId = bigint;
export interface Standing {
    goalDiff: bigint;
    played: bigint;
    wins: bigint;
    goalsFor: bigint;
    losses: bigint;
    goalsAgainst: bigint;
    teamId: TeamId;
    position: bigint;
    draws: bigint;
    points: bigint;
}
export type RefereeId = bigint;
export interface UserProfilePublic {
    favouriteTeamId?: TeamId;
    displayName: string;
    teamAffiliation: string;
    areaOfResidence: string;
    followedPlayerIds: Array<PlayerId>;
    followedTeamIds: Array<TeamId>;
}
export type TeamId = bigint;
export type PlayerId = bigint;
export type MatchId = bigint;
export interface Match {
    id: MatchId;
    matchTime: string;
    status: MatchStatus;
    awayTeamId: TeamId;
    homeTeamId: TeamId;
    joiners: Array<Principal>;
    homeScore: bigint;
    awayScore: bigint;
    matchDate: string;
}
export interface Official {
    id: OfficialId;
    area: string;
    name: string;
    role: string;
    email: string;
    phone: string;
}
export type ActivityId = bigint;
export interface ActivityItem {
    id: ActivityId;
    actorName: string;
    actionType: ActionType;
    entityId: bigint;
    timestamp: Timestamp;
    entityName: string;
    actorPrincipal?: Principal;
}
export interface NewsArticle {
    id: NewsId;
    title: string;
    content: string;
    date: string;
    emoji: string;
    excerpt: string;
    category: string;
}
export interface Referee {
    id: RefereeId;
    status: RefereeStatus;
    assignedMatchIds: Array<MatchId>;
    name: string;
    licenseNumber: string;
    phone: string;
}
export type OfficialId = bigint;
export interface Team {
    id: TeamId;
    name: string;
    wins: bigint;
    goalsFor: bigint;
    losses: bigint;
    emoji: string;
    abbreviation: string;
    goalsAgainst: bigint;
    draws: bigint;
}
export enum ActionType {
    goal = "goal",
    join = "join",
    status_change = "status_change",
    follow_team = "follow_team",
    follow_player = "follow_player"
}
export enum MatchStatus {
    scheduled = "scheduled",
    live = "live",
    finished = "finished"
}
export enum RefereeStatus {
    active = "active",
    inactive = "inactive"
}
export interface backendInterface {
    addMatch(homeTeamId: bigint, awayTeamId: bigint, matchDate: string, matchTime: string): Promise<bigint>;
    addNews(title: string, excerpt: string, content: string, category: string, date: string, emoji: string): Promise<bigint>;
    addOfficial(name: string, role: string, phone: string, email: string, area: string): Promise<bigint>;
    addPlayer(name: string, teamId: bigint, position: string, goals: bigint, assists: bigint, yellowCards: bigint): Promise<bigint>;
    addReferee(name: string, licenseNumber: string, phone: string): Promise<bigint>;
    addTeam(name: string, abbreviation: string, emoji: string): Promise<bigint>;
    assignRefereeToMatch(refereeId: bigint, matchId: bigint): Promise<boolean>;
    deleteNews(id: bigint): Promise<boolean>;
    deleteOfficial(id: bigint): Promise<boolean>;
    deletePlayer(id: bigint): Promise<boolean>;
    deleteReferee(id: bigint): Promise<boolean>;
    deleteTeam(id: bigint): Promise<boolean>;
    dismissActivity(activityId: bigint): Promise<void>;
    followPlayer(playerId: bigint): Promise<void>;
    followTeam(teamId: bigint): Promise<void>;
    getActivities(): Promise<Array<ActivityItem>>;
    getAllMatches(): Promise<Array<Match>>;
    getAllNews(): Promise<Array<NewsArticle>>;
    getAllOfficials(): Promise<Array<Official>>;
    getAllPlayers(): Promise<Array<Player>>;
    getAllReferees(): Promise<Array<Referee>>;
    getAllTeams(): Promise<Array<Team>>;
    getArticle(id: bigint): Promise<NewsArticle | null>;
    getMatch(id: bigint): Promise<Match | null>;
    getMatchesByTeam(teamId: bigint): Promise<Array<Match>>;
    getOfficial(id: bigint): Promise<Official | null>;
    getPlayer(id: bigint): Promise<Player | null>;
    getPlayersByTeam(teamId: bigint): Promise<Array<Player>>;
    getReferee(id: bigint): Promise<Referee | null>;
    getStandings(): Promise<Array<Standing>>;
    getTeam(id: bigint): Promise<Team | null>;
    getUserDismissed(): Promise<Array<bigint>>;
    getUserProfile(): Promise<UserProfilePublic>;
    hasJoinedMatch(matchId: bigint): Promise<boolean>;
    joinMatch(matchId: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    scheduleMatch(homeTeamId: bigint, awayTeamId: bigint, matchDate: string, matchTime: string): Promise<bigint>;
    setFavouriteTeam(teamId: bigint): Promise<void>;
    unassignRefereeFromMatch(refereeId: bigint, matchId: bigint): Promise<boolean>;
    unfollowPlayer(playerId: bigint): Promise<void>;
    unfollowTeam(teamId: bigint): Promise<void>;
    updateMatchScore(id: bigint, homeScore: bigint, awayScore: bigint): Promise<boolean>;
    updateMatchStatus(id: bigint, status: MatchStatus): Promise<boolean>;
    updateNews(id: bigint, title: string, excerpt: string, content: string, category: string, date: string, emoji: string): Promise<boolean>;
    updateOfficial(id: bigint, name: string, role: string, phone: string, email: string, area: string): Promise<boolean>;
    updatePlayer(id: bigint, name: string, teamId: bigint, position: string, goals: bigint, assists: bigint, yellowCards: bigint): Promise<boolean>;
    updateReferee(id: bigint, name: string, licenseNumber: string, status: RefereeStatus, phone: string): Promise<boolean>;
    updateTeam(id: bigint, name: string, abbreviation: string, emoji: string, wins: bigint, draws: bigint, losses: bigint, goalsFor: bigint, goalsAgainst: bigint): Promise<boolean>;
    updateUserProfile(displayName: string, area: string, teamAffiliation: string): Promise<void>;
}
import type { ActionType as _ActionType, ActivityId as _ActivityId, ActivityItem as _ActivityItem, Match as _Match, MatchId as _MatchId, MatchStatus as _MatchStatus, NewsArticle as _NewsArticle, Official as _Official, Player as _Player, PlayerId as _PlayerId, Referee as _Referee, RefereeId as _RefereeId, RefereeStatus as _RefereeStatus, Team as _Team, TeamId as _TeamId, Timestamp as _Timestamp, UserProfilePublic as _UserProfilePublic } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addMatch(arg0: bigint, arg1: bigint, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMatch(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMatch(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addNews(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addNews(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNews(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addOfficial(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addOfficial(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOfficial(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addPlayer(arg0: string, arg1: bigint, arg2: string, arg3: bigint, arg4: bigint, arg5: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPlayer(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPlayer(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addReferee(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addReferee(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReferee(arg0, arg1, arg2);
            return result;
        }
    }
    async addTeam(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTeam(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTeam(arg0, arg1, arg2);
            return result;
        }
    }
    async assignRefereeToMatch(arg0: bigint, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRefereeToMatch(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRefereeToMatch(arg0, arg1);
            return result;
        }
    }
    async deleteNews(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNews(arg0);
            return result;
        }
    }
    async deleteOfficial(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOfficial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOfficial(arg0);
            return result;
        }
    }
    async deletePlayer(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePlayer(arg0);
            return result;
        }
    }
    async deleteReferee(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReferee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReferee(arg0);
            return result;
        }
    }
    async deleteTeam(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTeam(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTeam(arg0);
            return result;
        }
    }
    async dismissActivity(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.dismissActivity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dismissActivity(arg0);
            return result;
        }
    }
    async followPlayer(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.followPlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followPlayer(arg0);
            return result;
        }
    }
    async followTeam(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.followTeam(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.followTeam(arg0);
            return result;
        }
    }
    async getActivities(): Promise<Array<ActivityItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActivities();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActivities();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMatches(): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMatches();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMatches();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNews(): Promise<Array<NewsArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNews();
            return result;
        }
    }
    async getAllOfficials(): Promise<Array<Official>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOfficials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOfficials();
            return result;
        }
    }
    async getAllPlayers(): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlayers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlayers();
            return result;
        }
    }
    async getAllReferees(): Promise<Array<Referee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReferees();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReferees();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTeams(): Promise<Array<Team>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTeams();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTeams();
            return result;
        }
    }
    async getArticle(arg0: bigint): Promise<NewsArticle | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticle(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticle(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatch(arg0: bigint): Promise<Match | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatch(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatch(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatchesByTeam(arg0: bigint): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchesByTeam(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchesByTeam(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOfficial(arg0: bigint): Promise<Official | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOfficial(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOfficial(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayer(arg0: bigint): Promise<Player | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayer(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayer(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayersByTeam(arg0: bigint): Promise<Array<Player>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayersByTeam(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayersByTeam(arg0);
            return result;
        }
    }
    async getReferee(arg0: bigint): Promise<Referee | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferee(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferee(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStandings(): Promise<Array<Standing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStandings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStandings();
            return result;
        }
    }
    async getTeam(arg0: bigint): Promise<Team | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeam(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeam(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserDismissed(): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserDismissed();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserDismissed();
            return result;
        }
    }
    async getUserProfile(): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_UserProfilePublic_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_UserProfilePublic_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasJoinedMatch(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasJoinedMatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasJoinedMatch(arg0);
            return result;
        }
    }
    async joinMatch(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.joinMatch(arg0);
                return from_candid_variant_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.joinMatch(arg0);
            return from_candid_variant_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async scheduleMatch(arg0: bigint, arg1: bigint, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.scheduleMatch(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.scheduleMatch(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async setFavouriteTeam(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setFavouriteTeam(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setFavouriteTeam(arg0);
            return result;
        }
    }
    async unassignRefereeFromMatch(arg0: bigint, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.unassignRefereeFromMatch(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unassignRefereeFromMatch(arg0, arg1);
            return result;
        }
    }
    async unfollowPlayer(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowPlayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowPlayer(arg0);
            return result;
        }
    }
    async unfollowTeam(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfollowTeam(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfollowTeam(arg0);
            return result;
        }
    }
    async updateMatchScore(arg0: bigint, arg1: bigint, arg2: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMatchScore(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMatchScore(arg0, arg1, arg2);
            return result;
        }
    }
    async updateMatchStatus(arg0: bigint, arg1: MatchStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMatchStatus(arg0, to_candid_MatchStatus_n27(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMatchStatus(arg0, to_candid_MatchStatus_n27(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateNews(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNews(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNews(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateOfficial(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOfficial(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOfficial(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updatePlayer(arg0: bigint, arg1: string, arg2: bigint, arg3: string, arg4: bigint, arg5: bigint, arg6: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePlayer(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePlayer(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateReferee(arg0: bigint, arg1: string, arg2: string, arg3: RefereeStatus, arg4: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReferee(arg0, arg1, arg2, to_candid_RefereeStatus_n29(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReferee(arg0, arg1, arg2, to_candid_RefereeStatus_n29(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async updateTeam(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint, arg8: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeam(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeam(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async updateUserProfile(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_ActionType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActionType): ActionType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_ActivityItem_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityItem): ActivityItem {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_MatchStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchStatus): MatchStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Match_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Match): Match {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_RefereeStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RefereeStatus): RefereeStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Referee_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Referee): Referee {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfilePublic_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfilePublic): UserProfilePublic {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NewsArticle]): NewsArticle | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Match]): Match | null {
    return value.length === 0 ? null : from_candid_Match_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Official]): Official | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Player]): Player | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Referee]): Referee | null {
    return value.length === 0 ? null : from_candid_Referee_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Team]): Team | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TeamId]): TeamId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _RefereeId;
    status: _RefereeStatus;
    assignedMatchIds: Array<_MatchId>;
    name: string;
    licenseNumber: string;
    phone: string;
}): {
    id: RefereeId;
    status: RefereeStatus;
    assignedMatchIds: Array<MatchId>;
    name: string;
    licenseNumber: string;
    phone: string;
} {
    return {
        id: value.id,
        status: from_candid_RefereeStatus_n15(_uploadFile, _downloadFile, value.status),
        assignedMatchIds: value.assignedMatchIds,
        name: value.name,
        licenseNumber: value.licenseNumber,
        phone: value.phone
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    favouriteTeamId: [] | [_TeamId];
    displayName: string;
    teamAffiliation: string;
    areaOfResidence: string;
    followedPlayerIds: Array<_PlayerId>;
    followedTeamIds: Array<_TeamId>;
}): {
    favouriteTeamId?: TeamId;
    displayName: string;
    teamAffiliation: string;
    areaOfResidence: string;
    followedPlayerIds: Array<PlayerId>;
    followedTeamIds: Array<TeamId>;
} {
    return {
        favouriteTeamId: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.favouriteTeamId)),
        displayName: value.displayName,
        teamAffiliation: value.teamAffiliation,
        areaOfResidence: value.areaOfResidence,
        followedPlayerIds: value.followedPlayerIds,
        followedTeamIds: value.followedTeamIds
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ActivityId;
    actorName: string;
    actionType: _ActionType;
    entityId: bigint;
    timestamp: _Timestamp;
    entityName: string;
    actorPrincipal: [] | [Principal];
}): {
    id: ActivityId;
    actorName: string;
    actionType: ActionType;
    entityId: bigint;
    timestamp: Timestamp;
    entityName: string;
    actorPrincipal?: Principal;
} {
    return {
        id: value.id,
        actorName: value.actorName,
        actionType: from_candid_ActionType_n4(_uploadFile, _downloadFile, value.actionType),
        entityId: value.entityId,
        timestamp: value.timestamp,
        entityName: value.entityName,
        actorPrincipal: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.actorPrincipal))
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MatchId;
    matchTime: string;
    status: _MatchStatus;
    awayTeamId: _TeamId;
    homeTeamId: _TeamId;
    joiners: Array<Principal>;
    homeScore: bigint;
    awayScore: bigint;
    matchDate: string;
}): {
    id: MatchId;
    matchTime: string;
    status: MatchStatus;
    awayTeamId: TeamId;
    homeTeamId: TeamId;
    joiners: Array<Principal>;
    homeScore: bigint;
    awayScore: bigint;
    matchDate: string;
} {
    return {
        id: value.id,
        matchTime: value.matchTime,
        status: from_candid_MatchStatus_n10(_uploadFile, _downloadFile, value.status),
        awayTeamId: value.awayTeamId,
        homeTeamId: value.homeTeamId,
        joiners: value.joiners,
        homeScore: value.homeScore,
        awayScore: value.awayScore,
        matchDate: value.matchDate
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    live: null;
} | {
    finished: null;
}): MatchStatus {
    return "scheduled" in value ? MatchStatus.scheduled : "live" in value ? MatchStatus.live : "finished" in value ? MatchStatus.finished : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
}): RefereeStatus {
    return "active" in value ? RefereeStatus.active : "inactive" in value ? RefereeStatus.inactive : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    goal: null;
} | {
    join: null;
} | {
    status_change: null;
} | {
    follow_team: null;
} | {
    follow_player: null;
}): ActionType {
    return "goal" in value ? ActionType.goal : "join" in value ? ActionType.join : "status_change" in value ? ActionType.status_change : "follow_team" in value ? ActionType.follow_team : "follow_player" in value ? ActionType.follow_player : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ActivityItem>): Array<ActivityItem> {
    return value.map((x)=>from_candid_ActivityItem_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Referee>): Array<Referee> {
    return value.map((x)=>from_candid_Referee_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Match>): Array<Match> {
    return value.map((x)=>from_candid_Match_n8(_uploadFile, _downloadFile, x));
}
function to_candid_MatchStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchStatus): _MatchStatus {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_RefereeStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RefereeStatus): _RefereeStatus {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchStatus): {
    scheduled: null;
} | {
    live: null;
} | {
    finished: null;
} {
    return value == MatchStatus.scheduled ? {
        scheduled: null
    } : value == MatchStatus.live ? {
        live: null
    } : value == MatchStatus.finished ? {
        finished: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RefereeStatus): {
    active: null;
} | {
    inactive: null;
} {
    return value == RefereeStatus.active ? {
        active: null
    } : value == RefereeStatus.inactive ? {
        inactive: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
